name: 💰 Auto-Claim Cwallet
on:
  schedule:
    - cron: '0 9 * * *'  # Jam 09.00 setiap hari
  workflow_dispatch:     # Bisa dijalankan manual

jobs:
  claim:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Dependencies
        run: |
          pip install --upgrade pip
          pip install selenium requests

      - name: Install Google Chrome
        run: |
          wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
          echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" | sudo tee /etc/apt/sources.list.d/google-chrome.list
          sudo apt-get update
          sudo apt-get install -y google-chrome-stable

      - name: Download ChromeDriver
        run: |
          CHROME_VERSION=$(google-chrome --version | grep -oE '([0-9]+\.){3}[0-9]+')
          CHROMEDRIVER_VERSION=$CHROME_VERSION
          wget -O /tmp/chromedriver.zip "https://chromedriver.storage.googleapis.com/${CHROMEDRIVER_VERSION}/chromedriver_linux64.zip"
          sudo unzip /tmp/chromedriver.zip -d /usr/local/bin/
          sudo chmod +x /usr/local/bin/chromedriver

      - name: Jalankan Bot
        run: python auto_cwallet.py
        env:
          CWALLET_EMAIL: ${{ secrets.CWALLET_EMAIL }}
          CWALLET_PASS: ${{ secrets.CWALLET_PASS }}
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          CHAT_ID: ${{ secrets.CHAT_ID }}
